strict: false
site_name: CAST AI Documentation
theme:
  name: 'material'
  favicon: img/favicon.ico
  custom_dir: overrides
  logo: img/cast-logo-dark-blue.svg
  palette:
    primary: white
    accent: indigo
  font:
    text: Nimbus Sans
extra_css:
  - stylesheets/extra.css
site_url: https://docs.cast.ai
repo_url: https://github.com/castai/docs
edit_uri: https://github.com/castai/docs/edit/main/docs/
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


extra:
  generator: false

nav:
  - 'Introduction': index.md
  - 'Getting started':
      - 'Create CAST cluster':
        - getting-started/overview.md
        - '1. Add cloud credentials':
            - getting-started/credentials/credentials-overview.md
            - getting-started/credentials/configuring-aws-credentials.md
            - getting-started/credentials/configuring-azure-credentials.md
            - getting-started/credentials/configuring-digitalocean-credentials.md
            - getting-started/credentials/configuring-gcp-credentials.md
        - getting-started/create-cluster.md
        - getting-started/deploy-application.md
      - 'Connect your cluster':
        - getting-started/external-cluster/overview.md
        - 'AWS EKS': getting-started/external-cluster/eks.md
  - 'Console overview':
      - console-overview/dashboard.md
      - console-overview/clusters.md
      - console-overview/nodes.md
      - console-overview/audit-log.md
      - console-overview/policies.md
      - console-overview/schedule.md
      - console-overview/logs.md
      - console-overview/api.md
  - 'Concepts':
      - concepts/how-it-works.md
      - concepts/cluster-lifecycle.md
      - concepts/cluster-architecture.md
      - concepts/cluster-infrastructure.md
      - concepts/vpn-overview.md
  - 'Guides':
      - 'Ingress': guides/ingress.md
      - 'Pod placement': guides/pod-pinning.md
      - guides/volumes.md
      - guides/autoscaling-policies.md
      - guides/hpa.md
      - guides/spot.md
      - guides/connect-to-node.md
  - 'API':
      - 'Introduction': api/overview.md
      - 'Authentication': api/authentication.md
      - 'Specification': api/specification.md
      - 'Terraform provider': api/terraform-provider.md
      - 'CLI': api/cli.md
  - 'Release notes': "https://cast.ai/release-notes/"
  - 'Service status': "https://status.cast.ai/"
  - 'Github': "https://github.com/castai"
  - 'CAST AI Console': "https://console.cast.ai"
