{
 "title": "Cortex cluster metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(castai_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Agent snapshots received (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(castai_autoscaler_agent_snapshots_received_total{castai_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Agent snapshots processed (5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(castai_autoscaler_agent_snapshots_processed_total{castai_cluster=\"$cluster\"}[5m]))",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Cluster cost monthly",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_total_cost_hourly{castai_cluster=\"$cluster\"}) * 720"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_pods_count{castai_cluster=\"$cluster\"})",
     "legendFormat": "All pods"
    },
    {
     "expr": "sum(castai_cluster_unschedulable_pods_count{castai_cluster=\"$cluster\"})",
     "legendFormat": "Unschedulable pods"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_requests_memory_bytes{castai_cluster=\"$cluster\"})",
     "legendFormat": "Memory requested"
    },
    {
     "expr": "sum(castai_cluster_provisioned_memory_bytes{castai_cluster=\"$cluster\"})",
     "legendFormat": "Memory provisioned"
    }
   ]
  },
  {
   "title": "Evictor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_evictor_node_target_count{castai_cluster=\"$cluster\"})",
     "legendFormat": "Targeted nodes"
    },
    {
     "expr": "sum(castai_evictor_pod_target_count{castai_cluster=\"$cluster\"})",
     "legendFormat": "Targeted pods"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_requests_cpu_cores{castai_cluster=\"$cluster\"}) / 1000",
     "legendFormat": "CPU requested"
    },
    {
     "expr": "sum(castai_cluster_provisioned_cpu_cores{castai_cluster=\"$cluster\"}) / 1000",
     "legendFormat": "CPU provisioned"
    }
   ]
  },
  {
   "title": "CPU utilization (cores)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(castai_cluster_requests_cpu_cores{castai_cluster=\"$cluster\"}) by (castai_node_type) / 1000",
     "legendFormat": "Requested {{castai_node_type}}"
    },
    {
     "expr": "sum(castai_cluster_provisioned_cpu_cores{castai_cluster=\"$cluster\"}) by (castai_node_type) / 1000",
     "legendFormat": "Provisioned {{castai_node_type}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_node_count{castai_cluster=\"$cluster\"})",
     "legendFormat": "All nodes"
    },
    {
     "expr": "sum(castai_cluster_node_count{castai_cluster=\"$cluster\", castai_node_type=\"spot\"})",
     "legendFormat": "Spot nodes"
    }
   ]
  },
  {
   "title": "Cluster Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(castai_cluster_requests_cpu_cores{castai_cluster=\"$cluster\"}) / sum(castai_cluster_provisioned_cpu_cores{castai_cluster=\"$cluster\"}) * 100",
     "legendFormat": "CPU requested"
    },
    {
     "expr": "sum(castai_cluster_requests_memory_bytes{castai_cluster=\"$cluster\"}) / sum(castai_cluster_provisioned_memory_bytes{castai_cluster=\"$cluster\"}) * 100",
     "legendFormat": "Memory requested"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(castai_cluster_requests_memory_bytes{castai_cluster=\"$cluster\"}) by (castai_node_type)",
     "legendFormat": "Requested {{castai_node_type}}"
    },
    {
     "expr": "sum(castai_cluster_provisioned_memory_bytes{castai_cluster=\"$cluster\"}) by (castai_node_type)",
     "legendFormat": "Provisioned {{castai_node_type}}"
    }
   ]
  }
 ]
}