name: Markdown lint
on:
  pull_request:
    branches:
      - main
jobs:
  markdown-link-check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          folder-path: "docs"
          file-path: "./README.md"
          check-modified-files-only: "yes"
          base-branch: "main"
  markdown-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: |
          gem install mdl
      - run: |
          mdl .
